experiment_name: "rf_baseline"

# Data settings
data:
  dataset_path: "multi-temporal-crop-classification-subset"
  flatten: true
  train_subset_size: 1000   
  test_subset_size: 1000

# Model settings
model:
  type: "RandomForest"
  hyperparameters:
    n_estimators: 100
    max_depth: null     # None in Python
    random_state: 42

# Visualization settings
visualization:
  colors:
    - "#0000FF"
    - "#000088"
    - "#00FF00"
    - "#00FFFF"
    - "#006600"
    - "#A9A9A9"
    - "#3399FF"
    - "#FFFF00"
    - "#FFCC00"
    - "#FFA500"
    - "#FF0000"
    - "#990000"
    - "#800000"
  num_samples: 2

# Output settings
output:
  save_model: false
  save_dir: "./experiments"